create PR comment action

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -11,14 +11,29 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
+      - uses: actions/setup-node@v1.4.0
+        with:
+          node-version: 12.x
       - run: |
-          npm install
-      - run: |
+          npm ci
           npm run all
+      - name: Verify no unstaged changes
+        run: |
+          if [[ "$(git status --porceain)" != "" ]]; then
+            git status
+            echo "::error::Unstaged changes detected.
+                  Run 'npm run all' before commit
+            exit 1
+          fi
   test: # make sure the action works on a clean machine without building
+    if: github.event_name = 'pull_request'
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
+      - id: prComment
       - uses: ./
         with:
-          milliseconds: 1000
+          repo-token: ${{ secrets.GITHUB_TOKEN }}
+          message: PR comment test
+      - name: Print comment URL
+        run: echo "Comment URL - ${{ steps.prComment.outputs.comment-url }}"
